markdown:   Pandoc
style:  davewhipp 
gems:
  - jekyll-pandoc
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: bibliography/references.bib
